"""add user avatar url

Revision ID: 21e7b70ae2be
Revises: 3edd00270a29
Create Date: 2026-09-20 01:51:13.853030

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21e7b70ae2be"
down_revision = "3edd00270a29"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("avatar_url", sa.String(length=512), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###
