"""add characters

Revision ID: 36626b33d2ba
Revises: 21e7b70ae2be
Create Date: 2026-09-20 02:16:50.863654

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36626b33d2ba"
down_revision = "21e7b70ae2be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("world_id", sa.UUID(), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("animal", sa.String(length=16), nullable=False),
        sa.Column("image_file_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("tint", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["image_file_id"],
            ["files.id"],
            name=op.f("fk_characters_image_file_id_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name=op.f("fk_characters_owner_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
            name=op.f("fk_characters_world_id_worlds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
    )
    op.create_index(
        op.f("ix_characters_owner_id"), "characters", ["owner_id"], unique=False
    )
    op.create_index(
        op.f("ix_characters_world_id"), "characters", ["world_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_characters_world_id"), table_name="characters")
    op.drop_index(op.f("ix_characters_owner_id"), table_name="characters")
    op.drop_table("characters")
    # ### end Alembic commands ###
