"""add references

Revision ID: 54fc49553c4e
Revises: 6b0ac62663c6
Create Date: 2026-09-20 09:54:56.278640

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "54fc49553c4e"
down_revision = "6b0ac62663c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "references",
        sa.Column("world_id", sa.UUID(), nullable=False),
        sa.Column("source_kind", sa.String(length=16), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("target_kind", sa.String(length=16), nullable=True),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
            name=op.f("fk_references_world_id_worlds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_references")),
        sa.UniqueConstraint("source_kind", "source_id", "label", name="uq_reference"),
    )
    op.create_index(
        "ix_reference_source", "references", ["source_kind", "source_id"], unique=False
    )
    op.create_index(
        "ix_reference_target", "references", ["target_kind", "target_id"], unique=False
    )
    op.create_index(
        op.f("ix_references_world_id"), "references", ["world_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_references_world_id"), table_name="references")
    op.drop_index("ix_reference_target", table_name="references")
    op.drop_index("ix_reference_source", table_name="references")
    op.drop_table("references")
    # ### end Alembic commands ###
