"""add stories

Revision ID: 77c9819cd869
Revises: c59f0d28a036
Create Date: 2026-09-20 09:36:38.519282

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "77c9819cd869"
down_revision = "c59f0d28a036"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stories",
        sa.Column("world_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("period_label", sa.String(length=255), nullable=True),
        sa.Column(
            "status", sa.Enum("OPEN", "CLOSED", name="story_status"), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("tint", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_stories_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
            name=op.f("fk_stories_world_id_worlds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stories")),
    )
    op.create_index(op.f("ix_stories_world_id"), "stories", ["world_id"], unique=False)
    op.create_table(
        "story_sessions",
        sa.Column("story_id", sa.UUID(), nullable=False),
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["sessions.id"],
            name=op.f("fk_story_sessions_session_id_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["story_id"],
            ["stories.id"],
            name=op.f("fk_story_sessions_story_id_stories"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "story_id", "session_id", name=op.f("pk_story_sessions")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("story_sessions")
    op.drop_index(op.f("ix_stories_world_id"), table_name="stories")
    op.drop_table("stories")
    # ### end Alembic commands ###
