"""add places

Revision ID: a4ad1c26f586
Revises: f8b67fbba717
Create Date: 2026-09-20 09:28:14.441102

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4ad1c26f586"
down_revision = "f8b67fbba717"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("world_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("shape", sa.String(length=16), nullable=False),
        sa.Column("image_file_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("tint", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_places_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["image_file_id"],
            ["files.id"],
            name=op.f("fk_places_image_file_id_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
            name=op.f("fk_places_world_id_worlds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_places")),
    )
    op.create_index(op.f("ix_places_world_id"), "places", ["world_id"], unique=False)
    op.add_column("worlds", sa.Column("current_place_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        op.f("fk_worlds_current_place_id_places"),
        "worlds",
        "places",
        ["current_place_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_worlds_current_place_id_places"), "worlds", type_="foreignkey"
    )
    op.drop_column("worlds", "current_place_id")
    op.drop_index(op.f("ix_places_world_id"), table_name="places")
    op.drop_table("places")
    # ### end Alembic commands ###
