"""add npcs

Revision ID: f8b67fbba717
Revises: 36626b33d2ba
Create Date: 2026-09-20 09:23:55.781894

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f8b67fbba717"
down_revision = "36626b33d2ba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "npcs",
        sa.Column("world_id", sa.UUID(), nullable=False),
        sa.Column("created_by_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("short_description", sa.Text(), nullable=False),
        sa.Column("animal", sa.String(length=16), nullable=False),
        sa.Column("image_file_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("locked", sa.Boolean(), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("tint", sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"], ["users.id"], name=op.f("fk_npcs_created_by_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["image_file_id"],
            ["files.id"],
            name=op.f("fk_npcs_image_file_id_files"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["world_id"],
            ["worlds.id"],
            name=op.f("fk_npcs_world_id_worlds"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_npcs")),
    )
    op.create_index(op.f("ix_npcs_world_id"), "npcs", ["world_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_npcs_world_id"), table_name="npcs")
    op.drop_table("npcs")
    # ### end Alembic commands ###
