/**
 * Generate the server-side Lucide icon registry (F20).
 *
 * The application used to ship the whole Lucide runtime (lucide.min.js, 417 KB)
 * and replace `<i data-lucide>` placeholders in the browser, which also meant an
 * htmx pass after every swap. Icons are now rendered on the server as inline
 * `<svg>` from the registry this script writes, so a reading page downloads no
 * icon JavaScript at all.
 *
 * The source is the pinned `lucide` devDependency (package.json). Run
 * `npm run icons` to regenerate; the script is deterministic, so a clean
 * checkout produces the committed `src/backend/icons.py` byte for byte. It is
 * never run during a build, so no floating `latest` asset can leak in.
 *
 * The names below are the inventory: every Lucide name the components, pages and
 * views pass to `common.Icon` / `common.Button` / `common.IconButton` /
 * `common.MenuItem` / `common.EmptyState`. A name that is not in this list and
 * not in the registry fails `tests/unit/test_icons.py`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { icons } from "lucide";

const require = createRequire(import.meta.url);
const { version } = require("lucide/package.json");

// Sorted so the generated file and its diff are stable.
const NAMES = [
  "arrow-right",
  "book-open",
  "calendar",
  "check",
  "chevron-down",
  "chevron-up",
  "circle-dot",
  "download",
  "file-text",
  "grid-2x2",
  "history",
  "home",
  "list",
  "lock",
  "lock-open",
  "log-out",
  "mail",
  "map",
  "map-pin",
  "map-pin-off",
  "menu",
  "palette",
  "panel-left-close",
  "pencil",
  "plus",
  "save",
  "settings",
  "shield",
  "star",
  "trash-2",
  "undo-2",
  "upload",
  "user",
  "user-plus",
  "users",
  "x",
];

const pascal = (name) =>
  name
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

/** One Lucide node (`["path", { d: "…" }]`) as an SVG element string. */
function element([tag, attrs]) {
  const rendered = Object.entries(attrs)
    .map(([key, value]) => ` ${key}="${String(value).replaceAll('"', "&quot;")}"`)
    .join("");
  return `<${tag}${rendered}/>`;
}

function body(name) {
  const node = icons[pascal(name)];
  if (!node) {
    throw new Error(`lucide@${version} has no icon named "${name}"`);
  }
  return node.map(element).join("");
}

/** A single-quoted Python string literal; Lucide paths never contain one. */
const pyLiteral = (value) =>
  "'" + value.replaceAll("\\", "\\\\").replaceAll("'", "\\'") + "'";

const entries = NAMES.map((name) => [name, body(name)]);
const widest = Math.max(...entries.map(([name]) => name.length + 2));
const table = entries
  .map(([name, svg]) => `    ${`"${name}":`.padEnd(widest)} ${pyLiteral(svg)},`)
  .join("\n");

const output = `"""Lucide UI icons, rendered on the server.

Generated by \`tools/build_icons.mjs\` from lucide@${version} (ISC licence, see
\`icons.LICENSE\`). Do not edit by hand: run \`npm run icons\`.

Each value is the body of a 24x24 Lucide icon, drawn as strokes that inherit
\`currentColor\`. \`common.Icon\` wraps it in the \`<svg>\` element, so an icon is
part of the server's first paint and an htmx fragment needs no icon pass.
"""

from markupsafe import Markup

ICONS: dict[str, str] = {
${table}
}

# The size vocabulary \`common.Icon\` accepts, in pixels, mapped to the class that
# carries the token. The pixel contract is unchanged: \`common.Button\` keeps its
# xs…xl icon map, and each pixel value here names the class that reads the
# matching \`--icon-*\` token in \`common/Icon.css\`.
SIZE_CLASSES: dict[int, str] = {
    16: "xs",
    18: "sm",
    20: "md",
    24: "lg",
    32: "xl",
    40: "2xl",
    48: "3xl",
}


class UnknownIcon(ValueError):
    """An icon name or size that is not in the registry."""


def icon_body(name: str) -> Markup:
    """The inner markup of one Lucide icon.

    An unknown name raises instead of rendering an empty square: a typo is a
    bug, and it fails the render (and the tests) rather than disappearing.
    """
    try:
        return Markup(ICONS[name])
    except KeyError:
        raise UnknownIcon(
            f"unknown icon {name!r}; add it to tools/build_icons.mjs "
            "and run npm run icons"
        ) from None


def icon_class(size: object) -> str:
    """The \`icon icon--<size>\` class for a pixel size.

    Callers keep passing pixels (\`size=24\`, \`:size="icon_sizes[button_size]"\`);
    the class is what carries the token, so no element gets a per-instance
    \`style\` attribute.
    """
    try:
        step = SIZE_CLASSES[int(size)]
    except (KeyError, TypeError, ValueError):
        raise UnknownIcon(
            f"unknown icon size {size!r}; allowed: {sorted(SIZE_CLASSES)}"
        ) from None
    return f"icon icon--{step}"
`;

writeFileSync(new URL("../src/backend/icons.py", import.meta.url), output);
console.log(`src/backend/icons.py: ${NAMES.length} icons from lucide@${version}`);
